export const filters = ["All", "In Progress", "Completed", "Beginner", "Intermediate", "Advanced"];

export const levelStyles = {
  Beginner: "bg-emerald-100 text-emerald-500",
  Intermediate: "bg-violet-100 text-violet-500",
  Advanced: "bg-emerald-100 text-emerald-500",
};
export const coursesData = [
  {
    id: 1,
    title: "Introduction to Graphic Design",
    level: "Beginner",
    image: "/images/g7.png",
    author: "Alex Morgan",
    enrolled: "4.8k Enrolled",
    img: "/images/ep.png",
    progress: null,
    button: null,
    active: true,
    status: null,
    role: "Graphic Design",
  },
  {
    id: 2,
    title: "Typography Essentials",
    level: "Intermediate",
    image: "/images/typography.png",
    author: "James Carter",
    enrolled: "",
    progress: 30,
    img: "/images/ep.png",
    button: "Resume",
    active: false,
    status: "In Progress",
    role: "Graphic Design",
  },
  {
    id: 3,
    title: "Mastering Adobe Illustration",
    level: "Advanced",
    image: "/images/g8.png",
    author: "James Carter",
    enrolled: "2k Enrolled",
    progress: null,
    img: "/images/james.png",
    button: null,
    active: false,
    status: null,
    role: "Adobe Tutor",
  },
  {
    id: 4,
    title: "Colour Theory & Psychology",
    level: "Beginner",
    image: "/images/colortheory.png",
    author: "Leon John",
    enrolled: "3.1k Enrolled",
    progress: null,
    img: "/images/leon.png",
    button: null,
    active: false,
    status: null,
    role: "Graphic Design",
  },
  {
    id: 5,
    title: "Advance Digital Illustration",
    level: "Intermediate",
    image: "/images/ad.png",
    author: "Laura Kim",
    enrolled: "2.7k Enrolled",
    progress: null,
    button: null,
    active: false,
    img: "/images/laura.png",
    status: null,
    role: "Graphic Design",
  },
  {
    id: 6,
    title: "Photoshop for Beginners",
    level: "Advanced",
    image: "/images/g14.png",
    author: "Emily Stone",
    enrolled: "5k Enrolled",
    progress: null,
    button: null,
    active: false,
    img: "/images/ep.png",
    status: "Completed",
    role: "Photoshop Tutor",
  },
  {
    id: 7,
    title: "Branding & Identity Design",
    level: "intermediate",
    image: "/images/g10.png",
    author: "Mark Stevens",
    enrolled: "5k Enrolled",
    progress: 60,
    button: null,
    active: false,
    img: "/images/mark.png",
    status: "In Progress",
    role: "Motion Design",
  },
  {
    id: 8,
    title: "social media design",
    level: "Advanced",
    image: "/images/social.png",
    author: "Emily Stone",
    enrolled: "5k Enrolled",
    progress: 40,
    button: null,
    active: false,
    img: "/images/ep.png",
    status: "In Progress",
    role: "Graphic Design",
  },
  {
    id: 9,
    title: "Layout & Grid System",
    level: "Beginner",
    image: "/images/g9.png",
    author: "Grey David",
    enrolled: "5k Enrolled",
    progress: null,
    button: null,
    active: false,
    img: "/images/grey.png",
    status: null,
    role: "Graphic Design",
  },
  {
    id: 10,
    title: "Design Thinking for beginners",
    level: "Advanced",
    image: "/images/typo.png",
    author: "Felicia Godswill",
    enrolled: "5k Enrolled",
    progress: null,
    button: null,
    active: false,
    img: "/images/felicia.png",
    status: "Completed",
    role: "Graphic Design",
  },
  {
    id: 11,
    title: "Canva Design for Beginners",
    level: "Beginner",
    image: "/images/canva.png",
    author: "Vivan Steve",
    enrolled: "900 Enrolled",
    progress: null,
    button: null,
    active: false,
    img: "/images/vivan.png",
    status: null,
    role: "Graphic Design",
  },
  {
    id: 12,
    title: "Visual Hierarchy & Composition",
    level: "Intermediate",
    image: "/images/visual.png",
    author: "James Carter",
    enrolled: "2k Enrolled",
    progress: null,
    button: null,
    active: false,
    img: "/images/james.png",
    status: null,
    role: "Graphic Design",
  },
  {
    id: 13,
    title: "Visual Branding",
    level: "Beginner",
    image: "/images/visualbrand.png",
    author: "James Carter",
    enrolled: "2k Enrolled",
    progress: 65,
    button: null,
    active: false,
    img: "/images/ep.png",
    status: null,
    role: "Graphic Design",
  },
];
